#!usr/bin/python

import re
#import find
re.compile('<title>(.*)</title>')
import sys

s = "ACCAATCACCAATCCACCAATCGACCAATCAACCAATCACCAATCACCAATCTTAGTACCAATCACCACCAATCCCACCACCAATCGCACCAATCACCAATCACCAATCACCAATCTAACCAATCCCACCAATCAACCAATCTACCAATCAGGGACCAATCTAGACCAATCCTTGTATAACCAATCACCAATCACCAATCTAACCAATCGAACCAATCGAGTTACCACCAATCGGAGAACCAATCACACCAATCGCCGACCAATCTTTCTCACCAATCACCAATCAAACCAATCATGGTTAAGACCAATCTGGAACACCAATCTAGACCAATCCAACCAATCCCTCCACCAATCGAACCAATCACCAATCAAACCAATCACCAATCAACCAATCCCAGTACCAATCGAACCAATCACCAATCGAACCAATCATACCAATCGCGAGAGGGCATGACCAATCTACCAATCGACCAATCTTCACCAATCAAGGACCAATCCTTCTGGGAGGGGTGACCAATCTCAACGGTACGACCAATCTTACCAATCACCAATCAACCAATCACCAATCAACCAATCAACCAATCGGGAACCAATCACCAATCTACCAATCACCAATCTTACCAATCGTGCGACCAATCTTACGACGACCAATCACCAATCCACCAATCATCACCAATCCTACCTAGTGAACCAATCACCAATCACTAAGCACCAATCTCACCAATCTACATCGCAAGACCAATCACCAATCGAGACCAATCAACCAATCCGTGGAGGGTCACCAATCGCACCAATCTGACCAATCACCAATCAACCAATCATACCAATCACCAATCACCAATCCTACCAATCAGCCTCACCAATCACACCAATCACCAATCTCACCAATCTACCAATCACACCAATCGACACCAATCCTGACCAATCACCAATCACCAATCCCGCCACCGCCGACCAATCGTACCAATCATACCAATCTATGGACCAATC"

t = "ACCAATCAC"
match = []
count = 0
diff = len(s) - len(t)

for i in range (diff):
    # find = s.find(t, count)
    # loc = find +1
    if s[i:i+len(t)] == t:
        match.append(str(i + 1))
    #match_point = map(str,match)
    #match_point.append(match)
print(' '.join(match))
#print(''.join(match_point))