#!usr/bin/python
import re
import array
import math
##this python script is solution to rosalind problem #GC_cont

#myfile = open("rosalind_revp.txt", "r")
#dna=myfile.read().replace('\n', '')

s = "CCACGTACCTCCAAAAGCGGTTAGAATTCCATAATCTCATGTTGTAGCCTATGCGGCTCCCATATCGTTAATCTGTCTGGGCCCGCAAACTAAAAACCCAACCGCTGGTCCGGACGAAACCCAGACGCTTTTTCTATGTTCTAAGCCATATTGTTAGACACAGTTGAACTGGGACGAGTACATGGCTATTCTAAAGCTGGCAGGCTGGAACCACATAAGATAAATGTTGTTAGCGCGGCCATTGAACTACGCATGCCGGTACCTGTAAGGCGCGCAGTGTGAGCGTTGGAGAGGGAGCTCGTCAGTAACGACCCTTGTCAGGTGGCATGGGAGCAGGCACCTTTGTTGCTGATCCCACGGGTGTTTCCCGTATCTACAGGAAGTCTCCGAGCAGGATTCTCTCCGAACCCGGGCCTTAACAGGAACGTATCGATACGAGGGTATCGTAACTGCGTGGAAGGTCACGTACGGGGGGGAAAACGACTCTACTGACGTTCACCCTCAACGGCAGCCATGGAGCAGCTTCTATCGGCCCACCCTTGTGTTCCCCCCTCGCGCTCAAATAACAACCCTAACCAGCTTTCAACAAAAGGGACGACATCTTCGTGAATGCTGATCCTACCTGCTTTCATGCAGGTCCCACCTGTTGGGGCCTTAGCCAGCAGGACGTCGAGCGAGCCTCAAATCTCTCAGCGCCTTGCGGGTGTATCGTCTTATGCACGGACCAGCATTAGCGGGTCTAGACACTCCGGTGCAATTTGAAGTCCCGAGTGACCGCGTATCTCCAGAGTTGCGGATGCTCGCCGGATGTCAGCAAAGAGTAGTGTCCTGGACGCACCTCACGTGCCCTCCCTCAGGGAACGTAAACGCATAGAACCGGCCGAGTAAAACTGGAAGATGTGCGTAAGAAAGCATGGCCTGCAGGTATCGAGG"
t = "CCTCGTAACGCGATCATCCGGTCTAATGCACTGTAATTAGGGTAGCGCCTCTCTGGCGCACATAGCGTTAGTTTTTAATGTGTTGGTGCCAGATAACCTAACAGATAGTAAGGACGCTATCGAGATTCTGGTCCTATACCCGCAGCAATAATGCGTAACTAAACAGTGTTGGGGTTAGTATATTACAAACACCTAGCACCTGGACTGTACTCGCACCCGCTAATTTTAAGGCGTACGAACCTTGATAATCGCCGCCCCGCCCCGGTGAAGAGCGTAGCACCGCCGATTGCAAAGGTGCGCACACGGTGGCCCACCTGACGGGGGTTGGGAGACCCGGCCGCTTCGATGTTAGCTCCGTGGGTGTATCCCAAAGCTATAGTCAGGATTCATCCAGCCGAGGTTAAGAACTAAAGTGGAATCGTGTACTTTTCGATACGTCCAAGGGGGTCCTATTCACCATGACATGAACGGGATTGAGGACGACTCTGGGCTTCTTAAGCCCTATTGGAATCTTTGGACTCGTACCGATCGTAAAACCATACTAGTGGCCTCACCAGTAAAATCAATAAATCTCACCCTACTTAAACACAAAAGATGCAGACGTGGTGAGTTCTGACTCTGTCTCCCCGCGCACATCTATGACAAACGCAGAGACCCGCAAACAGAAGGCCTGGCGGCGCCCCCTGTCGTGAGCAGCGTGCTCTAGCATCTTCGTACGTACGCCAACGCGTTACGGGCGCTAATAACCTAAGGGGGTTATAACGGGCCGATTCTCTCCTTGATTTCTCAAACGTGTTTCTTCATCGGATAGGTGCGTAGAGGCGAATGGCGCCCGCACCCTGAGGGTCCGCCCCACGGGAGATTAACTGCAAGCAAGTTAGCATATTTAAATGTATAGTGAGCTTAAAAGAGCATGGCCAACAATGAGGCATG"
#counter = []

def sequence_compare(s, t):
        len1 = len(s)
        #print (len1)
        len2 = len(t)
        ##print (len2)
        counter = 0
        #for pos in range (0, min(len1, len2)) :
        for i in range(len1):

            if s[i] != t[i]:
            	#print (s[i])
            	
              	counter += 1

              
        #print (s)
        #print (mismatches)
        #print (t)
        print (counter)
        #print (i)
sequence_compare(s,t)